version: "3.9"
networks:
  jhe_sso_one:
  sso_two_jhe_sso_one:
    external: true
services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - 8081:80
      - 7010:7010
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - redis
      - mysql
    container_name: jhe_sso_one_server
    networks:
      - jhe_sso_one
      - sso_two_jhe_sso_one
  mysql:
    image: mysql:8.0.1
    restart: unless-stopped
    tty: true
    container_name: mysql
    env_file:
      - ./env/mysql.env
    ports:
      - 3306:3306
    networks:
      - jhe_sso_one
    volumes:
      - /opt/mysql_data_sso_one:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: php_one_server
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - jhe_sso_one
      - sso_two_jhe_sso_one
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - jhe_sso_one
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - jhe_sso_one
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - jhe_sso_one
  npm:
    build:
      context: .
      dockerfile: dockerfiles/node.dockerfile
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    volumes:
      - ./src:/var/www/html
    networks:
      - jhe_sso_one